import { useNavigate } from "react-router";
import { ChevronRight } from "lucide-react";

const innovations = [
  {
    code: "HPC-7",
    name: "High-Performance Compound",
    headline: "Molecular Engineering at Scale",
    body: "HPC-7 is Hyperion's seventh-generation silica-polymer matrix. By adjusting the silane coupling agent concentration at the molecular level, we achieve a compound that stays soft and grippy when cold, yet resists thermal degradation at extreme operating temperatures. The result is consistent lap times from cold lap to hot lap.",
    stat: "18% more silica integration vs. gen 6",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=700&h=500&fit=crop&auto=format",
    tags: ["COMPOUND", "F1-DERIVED", "PATENT PENDING"],
  },
  {
    code: "ARS-2",
    name: "Aramid Reinforcement System",
    headline: "Lighter. Stiffer. More Precise.",
    body: "Conventional tire sidewalls use steel cords for stiffness. Hyperion's ARS-2 replaces outer sidewall cords with para-aramid fiber — the same material used in aerospace bulkheads. Aramid is 5× stiffer than steel at half the weight, which translates to razor-sharp turn-in response and dramatically reduced sidewall flex under lateral load.",
    stat: "5× stiffer, 50% lighter than steel equivalent",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=700&h=500&fit=crop&auto=format",
    tags: ["STRUCTURE", "AEROSPACE", "WEIGHT SAVING"],
  },
  {
    code: "ANC-1",
    name: "Active Noise Cancellation Rib",
    headline: "Silence, Engineered In.",
    body: "Road noise is generated by standing acoustic waves inside the tire cavity. ANC-1 is a patented internal polyurethane foam insert, tuned to specific resonant frequencies, that damps these waves before they propagate through the wheel into the cabin. Quantifiably 3 dB quieter than a comparable tire without the system.",
    stat: "3 dB reduction — perceived as 50% quieter",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=700&h=500&fit=crop&auto=format",
    tags: ["NVH", "COMFORT", "PATENTED"],
  },
  {
    code: "SIS-3",
    name: "Seal Inside System",
    headline: "Punctures That Don't Stop You.",
    body: "SIS-3 is a viscous sealant layer bonded to the inner liner. On puncture from objects up to 6mm diameter, the sealant flows into the wound under tire pressure and cures within 60 seconds. Available on P Zero and Cinturato variants, SIS-3 eliminates the need for a spare wheel without the compromised performance of a runflat.",
    stat: "Seals punctures up to 6mm in under 60 seconds",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&h=500&fit=crop&auto=format",
    tags: ["SAFETY", "SELF-SEALING", "OE SPEC"],
  },
];

const timeline = [
  { year: "1872", event: "Giovanni Battista Hyperion founds the company in Milan with a vision for precision rubber products." },
  { year: "1907", event: "Hyperion supplies the first automotive tires for the Coppa Florio race — motorsport DNA from day one." },
  { year: "1950", event: "First Formula 1 season. Hyperion tires compete in the inaugural World Drivers' Championship." },
  { year: "1974", event: "Introduction of the P7 — the world's first low-profile high-performance road tire." },
  { year: "1986", event: "Launch of P Zero. Immediately adopted by Ferrari, Lamborghini, and Porsche as OE fitment." },
  { year: "2011", event: "Named exclusive Formula 1 tire supplier. Partnership continues to the present day." },
  { year: "2019", event: "HPC-7 compound introduced — first commercially available tire compound developed using AI-assisted molecular simulation." },
  { year: "2024", event: "P Zero Corsa launched. Most capable road-legal Hyperion tire in 150 years of production." },
];

export default function Technology() {
  const navigate = useNavigate();

  return (
    <div>
      {/* Header */}
      <div className="relative overflow-hidden border-b border-border">
        <img
          src="https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1600&h=600&fit=crop&auto=format"
          alt="Tire compound research"
          className="w-full h-72 md:h-96 object-cover opacity-25"
        />
        <div className="absolute inset-0 bg-gradient-to-r from-background via-background/80 to-transparent" />
        <div className="absolute inset-0 flex flex-col justify-end px-6 md:px-12 pb-12">
          <div className="text-xs text-primary tracking-widest mb-4" style={{ fontFamily: "'DM Mono', monospace" }}>
            RESEARCH & DEVELOPMENT
          </div>
          <h1
            className="text-6xl md:text-9xl font-black leading-none tracking-tighter"
            style={{ fontFamily: "'Barlow Condensed', sans-serif" }}
          >
            TECHNOLOGY.
          </h1>
        </div>
        <div className="absolute right-0 top-0 h-full w-1 bg-primary opacity-60" />
      </div>

      {/* Intro */}
      <div className="px-6 md:px-12 py-16 border-b border-border grid grid-cols-1 lg:grid-cols-3 gap-12">
        <div className="lg:col-span-2">
          <p className="text-xl md:text-2xl font-light leading-relaxed text-foreground">
            Every Hyperion tire is the physical embodiment of decades of racing intelligence, material science breakthroughs, and obsessive refinement. We don{"'"}t manufacture tires — we engineer contact patches.
          </p>
        </div>
        <div className="flex flex-col gap-6">
          {[
            { label: "ACTIVE PATENTS", value: "340+" },
            { label: "R&D ENGINEERS", value: "1,900" },
            { label: "TEST KM / YEAR", value: "12M" },
          ].map((s) => (
            <div key={s.label} className="border-l-2 border-primary pl-4">
              <div className="text-3xl font-black text-primary" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{s.value}</div>
              <div className="text-xs text-muted-foreground tracking-widest" style={{ fontFamily: "'DM Mono', monospace" }}>{s.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Innovations */}
      <div className="px-6 md:px-12 py-20">
        <div className="text-xs text-primary tracking-widest mb-12" style={{ fontFamily: "'DM Mono', monospace" }}>
          CORE INNOVATIONS
        </div>
        <div className="flex flex-col gap-0 border border-border">
          {innovations.map((inn, i) => (
            <div key={i} className="grid grid-cols-1 lg:grid-cols-2 border-b border-border last:border-b-0">
              <div className="relative overflow-hidden min-h-56 bg-secondary">
                <img src={inn.image} alt={inn.name} className="w-full h-full object-cover opacity-60" />
                <div className="absolute inset-0 bg-gradient-to-r from-background/60 to-transparent" />
                <div className="absolute top-4 left-4 flex gap-2 flex-wrap">
                  {inn.tags.map((tag) => (
                    <span key={tag} className="text-xs font-bold tracking-widest px-2 py-1 bg-primary/90 text-white" style={{ fontFamily: "'DM Mono', monospace" }}>
                      {tag}
                    </span>
                  ))}
                </div>
                <div className="absolute bottom-4 left-4 text-5xl font-black opacity-20" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>
                  {inn.code}
                </div>
              </div>
              <div className="p-10 flex flex-col justify-between">
                <div>
                  <div className="text-xs text-muted-foreground tracking-widest mb-2" style={{ fontFamily: "'DM Mono', monospace" }}>{inn.code} — {inn.name.toUpperCase()}</div>
                  <h3 className="text-4xl font-black leading-tight tracking-tighter mb-4" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{inn.headline}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed font-light">{inn.body}</p>
                </div>
                <div className="mt-6 border-l-2 border-primary pl-4">
                  <div className="text-xs text-muted-foreground tracking-widest mb-1" style={{ fontFamily: "'DM Mono', monospace" }}>KEY METRIC</div>
                  <div className="text-sm font-bold text-foreground">{inn.stat}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Timeline */}
      <div className="border-t border-border bg-card px-6 md:px-12 py-20">
        <div className="text-xs text-primary tracking-widest mb-12" style={{ fontFamily: "'DM Mono', monospace" }}>
          150 YEARS OF INNOVATION
        </div>
        <div className="flex flex-col gap-0 border border-border">
          {timeline.map((item, i) => (
            <div key={i} className="flex gap-0 border-b border-border last:border-b-0 hover:bg-secondary transition-colors">
              <div
                className="flex-shrink-0 w-24 md:w-32 px-6 py-5 border-r border-border flex items-center"
                style={{ fontFamily: "'Barlow Condensed', sans-serif" }}
              >
                <span className="text-2xl font-black text-primary">{item.year}</span>
              </div>
              <div className="px-6 py-5 flex items-center">
                <p className="text-sm text-muted-foreground font-light leading-relaxed">{item.event}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* CTA */}
      <div className="border-t border-border px-6 md:px-12 py-16 flex flex-col md:flex-row items-start md:items-center justify-between gap-8">
        <div>
          <div className="text-xs text-primary tracking-widest mb-3" style={{ fontFamily: "'DM Mono', monospace" }}>SEE THE TECHNOLOGY IN ACTION</div>
          <h2 className="text-4xl md:text-6xl font-black tracking-tighter leading-none" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>
            EXPLORE OUR RACING<br />PROGRAM.
          </h2>
        </div>
        <button
          onClick={() => navigate("/racing")}
          className="flex items-center gap-3 bg-primary text-primary-foreground px-10 py-4 text-sm font-bold tracking-widest hover:bg-red-700 transition-colors group flex-shrink-0"
        >
          RACING <ChevronRight size={16} className="group-hover:translate-x-1 transition-transform" />
        </button>
      </div>
    </div>
  );
}
